export const actionTypes = {
    FETCHING_START: "FETCHING_START",
    FETCHING_END: "FETCHING_END",
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_CART: 'REMOVE_CART',
    ADD_TO_BOOKMARK: 'ADD_TO_BOOKMARK',
    REMOVE_BOOKMARK: 'REMOVE_BOOKMARK',
    SORTING_VALUE: 'SORTING_VALUE',
    SORTING_COURSE: 'SORTING_COURSE',
    CHECKOUT: 'CHECKOUT'
}